// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://frxvpishprygdksbgziz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeHZwaXNocHJ5Z2Rrc2Jneml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1NjMyMDUsImV4cCI6MjA0NzEzOTIwNX0.XIuU2O185qp6oxJr80natMsSJEcOqEmOTIP0fIzpsD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);